Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -4,10 +4,8 @@ on:
   push:
     branches: [ "main" ]
 
-
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
@@ -30,13 +28,13 @@ jobs:
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
-          
+
       - name: Run chmod to make gradlew executable
         run: chmod +x ./gradlew
-        
+
       - name: Build with Gradle
         run: ./gradlew build -x test
-          
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -50,7 +48,7 @@ jobs:
       - name: Push Docker Image to Docker Hub
         run: |
           docker push ${{ secrets.IMAGE_NAME }}
-          
+
       - name: Deploy
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -59,10 +57,17 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           port: 22
           script: |
-            docker stop gratitude-container
-            docker rm -f gratitude-container
+            # Stop and remove existing container if it exists
+            docker stop gratitude-container || true
+            docker rm -f gratitude-container || true
+
+            # Pull the latest image
             docker pull ${{ secrets.IMAGE_NAME }}
+
+            # Run the Docker container with environment variable
             docker run -d -p 8080:8080 --name gratitude-container \
-              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \  # 환경 변수 추가
+              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
               ${{ secrets.IMAGE_NAME }}
+
+            # Clean up unused Docker images
             docker image prune -f
